# Generated by Django 3.0 on 2020-05-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Cтатус'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Cтатус'),
        ),
    ]
