# Generated by Django 3.0 on 2020-05-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200515_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='recomendations',
        ),
        migrations.AlterField(
            model_name='resume',
            name='portfolio_url',
            field=models.TextField(blank=True, verbose_name='Портфолио'),
        ),
    ]
