# Generated by Django 3.0 on 2020-05-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200515_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Cтатус'),
        ),
    ]
